name = "hone-relay"
main = "src/index.js"
compatibility_date = "2026-09-01"

[[durable_objects.bindings]]
name = "SESSIONS"        
class_name = "Session"  

[[migrations]]
tag = "v1"
new_sqlite_classes = ["Session"]   # le nom de ta classe
